# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9d6e9882bae3028e6e5f23bc3df4ff78719af5dd00c0554eab68d9a2ca021bb3dcaa34106472a75e921cb8f9701df9b736783f49db18a6423aea5747a764e19

test:
  secret_key_base: 53859cc30c7a6e74ec9906449bee000da97f8f72978099a6b53fb8e8f0d4e4d2da16df350a05191953443d865ddcf3d68299470c7bcac46963b3e01b79e833e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
